import { MdKitchen } from "react-icons/md";

export const history = [
  {
    id: 1,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Comment",
  },
  {
    id: 2,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Simple comment",
  },
  {
    id: 3,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "I spend to much",
  },
  {
    id: 4,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Another comment",
  },
  {
    id: 5,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Another comment",
  },
  {
    id: 6,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Another comment",
  },
  {
    id: 7,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Another comment",
  },
  {
    id: 8,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Another comment",
  },

  {
    id: 9,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Another comment",
  },
  {
    id: 10,
    Icon: MdKitchen,
    category: "Jedzenie dom",
    date: new Date("2021-10-10"),
    action: -50,
    comment: "Another comment",
  },
];
